name: Bazel tests

on: [push, pull_request]
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  bazel-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run Bazel tests
        run: bazel test ...:all --test_output=all --action_env=WGKEX_CONFIG_FILE=`pwd`/wgkex.yaml.example
      - name: Python coverage
        run: |
          sudo apt-get install -y lcov
          mkdir "${GITHUB_WORKSPACE}/src"
          cd "${GITHUB_WORKSPACE}/src"
          curl -L https://files.pythonhosted.org/packages/24/56/95b7e30fa389756cb56630faa728da46a27b8c6eb46f9d557c68fff12b65/coverage-7.13.4.tar.gz | tar xvz
          cd "${GITHUB_WORKSPACE}"
          bazel coverage --combined_report=lcov --java_runtime_version=remotejdk_11 -t- --instrument_test_targets \
            --test_output=errors --linkopt=--coverage --linkopt=-lc \
            --test_env=PYTHON_COVERAGE=${GITHUB_WORKSPACE}/src/coverage-7.13.1/__main__.py \
            --test_verbose_timeout_warnings --define=config_file=test ...:all
      - name: Coveralls
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: bazel-out/_coverage/_coverage_report.dat
